/**
 * Unified ABI export entrypoint
 */
const { ERC20_BALANCE_ABI, ERC20_TRANSFER_ABI, TOKEN_ALLOWANCE_ABI } = require('./erc20')
const {
  UNISWAP_ROUTER_ABI,
  FACTORY_ABI,
  PAIR_ABI,
  CL_POOL_MANAGER_ABI
} = require('./router')
const { WRAP_SWAPER_ABI, WRAP_SWAPER2_ABI } = require('./wrapSwaper')
const { IPSHARE_ABI } = require('./ipshare')
const {
  TOKEN_BUY_ABI,
  TOKEN1_BUY_ABI,
  TOKEN5_BUY_ABI,
  TOKEN8_BUY_ABI,
  TOKEN_SELL_ABI,
  TOKEN8_SELL_ABI,
  TOKEN_SUPPLY_ABI,
  TOKEN_NUTBOX_ABI,
  PUMP_CREATE_ABI,
  PUMP_QUOTE_ABI
} = require('./tokenPump')
const {
  NUTBOX_COMMUNITY_ABI,
  NUTBOX_POOL_ABI,
  ERC20_STAKING_POOL_ABI,
  ERC20_LOCKING_POOL_ABI,
  ERC1155_STAKING_POOL_ABI,
  SOCIAL_CURATION_POOL_ABI,
  NUTBOX_COMMITTEE_ABI,
  ERC1155_APPROVAL_ABI
} = require('./nutbox')

module.exports = {
  ERC20_BALANCE_ABI,
  ERC20_TRANSFER_ABI,
  TOKEN_ALLOWANCE_ABI,
  UNISWAP_ROUTER_ABI,
  FACTORY_ABI,
  PAIR_ABI,
  CL_POOL_MANAGER_ABI,
  WRAP_SWAPER_ABI,
  WRAP_SWAPER2_ABI,
  IPSHARE_ABI,
  TOKEN_BUY_ABI,
  TOKEN1_BUY_ABI,
  TOKEN5_BUY_ABI,
  TOKEN8_BUY_ABI,
  TOKEN_SELL_ABI,
  TOKEN8_SELL_ABI,
  TOKEN_SUPPLY_ABI,
  TOKEN_NUTBOX_ABI,
  PUMP_CREATE_ABI,
  PUMP_QUOTE_ABI,
  NUTBOX_COMMUNITY_ABI,
  NUTBOX_POOL_ABI,
  ERC20_STAKING_POOL_ABI,
  ERC20_LOCKING_POOL_ABI,
  ERC1155_STAKING_POOL_ABI,
  SOCIAL_CURATION_POOL_ABI,
  NUTBOX_COMMITTEE_ABI,
  ERC1155_APPROVAL_ABI
}
